<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <PlatformTarget>x64</PlatformTarget>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>1.0.0</Version>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>VVUP.Base</Title>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugSymbols>true</DebugSymbols>
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <PropertyGroup>
        <DependencyPath>$(MSBuildThisFileDirectory)../bin/dependencies/</DependencyPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony"/>
        <PackageReference Include="ExMod.Exiled"/>
    </ItemGroup>

    <Target Name="CopyDependencies" AfterTargets="Build">
        <ItemGroup>
            <DependenciesToCopy Include="$(OutputPath)0Harmony.dll"/>
        </ItemGroup>

        <Copy SourceFiles="@(DependenciesToCopy)"
              DestinationFolder="$(DependencyPath)"
              SkipUnchangedFiles="true"/>
    </Target>
</Project>