<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugSymbols>true</DebugSymbols>
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../VVUP.Base/VVUP.Base.csproj"/>
    </ItemGroup>


    <ItemGroup>
      <PackageReference Remove="RueI" />
    </ItemGroup>
</Project>