<Project>
    <PropertyGroup>
        <GenerateAssemblyInformationVersionAttribute>false</GenerateAssemblyInformationVersionAttribute>
        <SharedBinPath>$(MSBuildThisFileDirectory)bin/</SharedBinPath>
        <NoWarn>MSB3277</NoWarn>
    </PropertyGroup>

    <Target Name="CopyToSharedBin" AfterTargets="Build">
        <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
              DestinationFolder="$(SharedBinPath)"
              SkipUnchangedFiles="true"/>
    </Target>

    <PropertyGroup>
        <Authors>Vicious Vikki</Authors>
        <Version Condition="$(Version) == ''">4.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp" Publicize="true"/>
        <Reference Include="Assembly-CSharp-firstpass"/>
        <Reference Include="CommandSystem.Core"/>
        <Reference Include="mscorlib"/>
        <Reference Include="Mirror" Publicize="true"/>
        <Reference Include="NorthwoodLib"/>
        <Reference Include="Unity.TextMeshPro"/>
        <Reference Include="UnityEngine"/>
        <Reference Include="UnityEngine.AnimationModule"/>
        <Reference Include="UnityEngine.CoreModule"/>
        <Reference Include="UnityEngine.PhysicsModule"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ExMod.Exiled"/>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" PrivateAssets="all" ExcludeAssets="runtime" ReferenceOutputAssembly="false" Private="true"/>
    </ItemGroup>
</Project>
