name: Pull Request Open

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-review-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Request review from repo owner
        uses: peter-evans/review-request@v3
        with:
          reviewers: SnivyFilms

      - name: Assign PR author
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [pr.user.login]
            });
