name: Pull Request Open

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

permissions:
  pull-requests: write
  issues: write

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from repo owner
        uses: peter-evans/review-request@v3
        with:
          reviewers: SnivyFilms

      - name: Assign PR author as assignee
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [context.actor]
            });
