name: Build and Publish Artifact

on:
  - push

env:
  EXILED_REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  EXILED_REFERENCES: ${{ github.workspace }}/refs

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          vs-prerelease: false
          msbuild-architecture: x64
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Exiled References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES }} -Force
      - name: Restore packages
        run: nuget restore ${{ github.workspace }}/SnivysUltimatePackage.sln
      - name: Build
        run: msbuild.exe ${{ github.workspace }}/SnivysUltimatePackage.sln /p:Configuration=Release /p:Platform="Any CPU"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnivysUltimatePackage
          path: ${{ github.workspace }}/Build
          if-no-files-found: error
