name: Build and Publish DLLs on Release

on:
  release:
    types: [published]

env:
  EXILED_REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  EXILED_REFERENCES: ${{ github.workspace }}/refs

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          vs-prerelease: false
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Exiled References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES }} -Force

      - name: Restore packages
        run: nuget restore ${{ github.workspace }}/SnivysUltimatePackage.sln

      - name: Build
        run: msbuild.exe ${{ github.workspace }}/SnivysUltimatePackage.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Gather plugin DLLs
        shell: pwsh
        run: |
          # Create output directory
          $outputDir = Join-Path $env:GITHUB_WORKSPACE "artifacts"
          New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
          
          # Find all VVUP DLLs in the build output
          Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter "VVUP.*.dll" | ForEach-Object {
            Write-Host "Found plugin: $($_.FullName)"
            Copy-Item -Path $_.FullName -Destination $outputDir -Force
          }
          
          # List files found
          Write-Host "Artifacts ready for upload:"
          Get-ChildItem $outputDir

      - name: Upload built plugins to Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
